import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { 
  FileText, 
  Download, 
  Loader2,
  CheckCircle2
} from 'lucide-react';
import { motion } from 'framer-motion';

const reportSections = [
  { id: 'patient_info', label: 'Patient Input Parameters', default: true },
  { id: 'risk_prediction', label: 'Risk Prediction Results', default: true },
  { id: 'probability', label: 'Probability Distribution', default: true },
  { id: 'explainability', label: 'Explainability Summary (SHAP)', default: true },
  { id: 'recommendations', label: 'Clinical Recommendations', default: true },
  { id: 'model_confidence', label: 'Model Confidence & Consensus', default: false },
  { id: 'population_context', label: 'Population Risk Context', default: false },
  { id: 'annotations', label: 'Clinical Annotations', default: false },
];

export default function ExportReport({ formData, result }) {
  const [selectedSections, setSelectedSections] = useState(
    reportSections.filter(s => s.default).map(s => s.id)
  );
  const [isGenerating, setIsGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);

  const toggleSection = (id) => {
    if (selectedSections.includes(id)) {
      setSelectedSections(selectedSections.filter(s => s !== id));
    } else {
      setSelectedSections([...selectedSections, id]);
    }
  };

  const generateReport = async () => {
    setIsGenerating(true);
    
    // Simulate report generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Create report content
    const reportContent = `
MATERNAL HEALTH RISK ASSESSMENT REPORT
======================================
Generated: ${new Date().toLocaleString()}

${selectedSections.includes('patient_info') ? `
PATIENT INPUT PARAMETERS
------------------------
Age: ${formData?.age || 'N/A'} years
Systolic BP: ${formData?.systolicBP || 'N/A'} mmHg
Diastolic BP: ${formData?.diastolicBP || 'N/A'} mmHg
Blood Sugar: ${formData?.bloodSugar || 'N/A'} mg/dL
Body Temperature: ${formData?.bodyTemp || 'N/A'} °F
Heart Rate: ${formData?.heartRate || 'N/A'} bpm
` : ''}

${selectedSections.includes('risk_prediction') ? `
RISK PREDICTION RESULTS
-----------------------
Risk Level: ${result?.riskLevel?.toUpperCase() || 'N/A'}
Confidence: ${result?.confidence || 'N/A'}%
` : ''}

${selectedSections.includes('probability') ? `
PROBABILITY DISTRIBUTION
------------------------
Low Risk: ${result?.probabilities?.low || 'N/A'}%
Medium Risk: ${result?.probabilities?.mid || 'N/A'}%
High Risk: ${result?.probabilities?.high || 'N/A'}%
` : ''}

${selectedSections.includes('recommendations') ? `
CLINICAL RECOMMENDATIONS
------------------------
Based on the risk assessment, the following actions are recommended:
${result?.riskLevel === 'high' 
  ? '• Urgent consultation with maternal-fetal medicine specialist\n• Weekly or more frequent prenatal monitoring\n• Continuous blood pressure and glucose monitoring'
  : result?.riskLevel === 'mid'
  ? '• Increase prenatal visit frequency to every 2 weeks\n• Monitor blood pressure at home daily\n• Review medication and supplement regimen'
  : '• Continue standard prenatal care protocol\n• Schedule routine prenatal visits every 4 weeks\n• Maintain regular physical activity as advised'
}
` : ''}

${selectedSections.includes('explainability') ? `
EXPLAINABILITY SUMMARY
----------------------
Key contributing factors to the risk assessment:
• Blood pressure levels
• Blood glucose levels
• Maternal age
• Heart rate patterns
• Body temperature

Note: Full SHAP analysis available in the clinical dashboard.
` : ''}

DISCLAIMER
----------
This report is generated by an AI-assisted clinical decision support tool.
It is intended for screening purposes only and should not replace professional
medical diagnosis or clinical judgment. Always consult with qualified healthcare
providers for medical advice, diagnosis, and treatment.

======================================
End of Report
    `;

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `maternal_risk_report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setIsGenerating(false);
    setGenerated(true);
    setTimeout(() => setGenerated(false), 3000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
    >
      <Card className="bg-slate-800/50 backdrop-blur-xl border border-white/10">
        <CardHeader className="border-b border-white/10">
          <CardTitle className="flex items-center gap-3 text-white">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 flex items-center justify-center">
              <FileText className="w-5 h-5 text-white" />
            </div>
            Export Patient Report
          </CardTitle>
        </CardHeader>
        <CardContent className="p-6">
          <p className="text-sm text-slate-400 mb-4">
            Select sections to include in the downloadable report:
          </p>

          <div className="space-y-3 mb-6">
            {reportSections.map((section) => (
              <label
                key={section.id}
                className="flex items-center gap-3 p-3 rounded-lg bg-slate-700/30 border border-slate-600/30 cursor-pointer hover:bg-slate-700/50 transition-colors"
              >
                <Checkbox
                  checked={selectedSections.includes(section.id)}
                  onCheckedChange={() => toggleSection(section.id)}
                  className="border-slate-500 data-[state=checked]:bg-teal-500 data-[state=checked]:border-teal-500"
                />
                <span className="text-sm text-slate-300">{section.label}</span>
              </label>
            ))}
          </div>

          <Button
            onClick={generateReport}
            disabled={isGenerating || selectedSections.length === 0}
            className={`w-full ${generated ? 'bg-emerald-500 hover:bg-emerald-400' : 'bg-teal-500 hover:bg-teal-400'} text-white`}
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Generating Report...
              </>
            ) : generated ? (
              <>
                <CheckCircle2 className="w-4 h-4 mr-2" />
                Report Downloaded!
              </>
            ) : (
              <>
                <Download className="w-4 h-4 mr-2" />
                Download Report
              </>
            )}
          </Button>

          <p className="text-xs text-slate-500 mt-4 text-center">
            Report will be downloaded as a text file. PDF export coming soon.
          </p>
        </CardContent>
      </Card>
    </motion.div>
  );
}